CREATE TABLE `t_tiny_url` (
  `ID`          VARCHAR(40)  NOT NULL,
  `TINY_URL`    VARCHAR(20)  DEFAULT NULL,
  `LONG_URL`    VARCHAR(255) DEFAULT NULL,
  `CREATE_TIME` DATETIME     DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
